Map: specify use of CryptoUtil.SHA1Hash(byte[])
	/home/buildozer/git/aports/testing/openra/src/OpenRA-56e6a9e6dc4f649b9c5939847e5673c04b3670c1/OpenRA.Game/Map/Map.cs(285,24): error CS0121:
	The call is ambiguous between the following methods or properties:
	'CryptoUtil.SHA1Hash(byte[])' and 'CryptoUtil.SHA1Hash(string)'
	[/home/buildozer/git/aports/testing/openra/src/OpenRA-56e6a9e6dc4f649b9c5939847e5673c04b3670c1/OpenRA.Game/OpenRA.Game.csproj]

Fixes: 79454d8fd29b ("Fix IDE0028, IDE0300, IDE0301, IDE0302, IDE0303, IDE0304.")
Signed-off-by: Achill Gilgenast <achill@achill.org>